"""Re-render REPORT.md section 4 from budget.py output."""
import os, re, subprocess, sys
D = os.path.dirname(os.path.abspath(__file__))
md = subprocess.run([sys.executable, os.path.join(D, "budget.py")] + sys.argv[1:], capture_output=True, text=True, check=True).stdout
est = "" if os.path.exists(os.path.join(D, "results/t1/awq_135m_s0_g64.json")) and '"quantize"' in open(os.path.join(D, "results/t1/awq_135m_s0_g64.json")).read() else \
    f"\n> AWQ 135M quantize time above is an **estimate** ({sys.argv[1]} s) from the measured per-layer pace (≈3.85 min/layer × 30 layers); see §3.\n"
sec = f"""## 4. Extrapolated CPU budget for the full design

Generated by `feasibility/budget.py` from the measured unit costs (single job on the 4-vCPU VM; 360M lm-eval time
is extrapolated with the measured 360M/135M forward-cost ratio from the ppl evals). Arc+hellaswag time scales
linearly in items (limit 100 → 122 s, limit 200 → 242 s). GPTQ W3 is assumed to cost the same as W4 (not measured).
{est}
{md}
**Verdict: the full design does not fit in an interactive session** — not even close (sessions are reclaimed when
idle and background jobs do not survive). Individual cells (37–85 min for GPTQ, 2–5 h for AWQ) do fit, so the work
must be organised as a restartable job queue that writes each cell's JSON as soon as it finishes, ideally over
several parallel sessions/VMs.

**What I would cut / change, in order of payoff:**
1. **AWQ is the cost driver** (≈ 12× GPTQ on CPU, and only works with g64 on SmolLM2 — see §6). Keep AWQ at 3 seeds
   (or drop it from the CPU arm) and keep GPTQ W4 as the 10-seed workhorse.
2. Quantize GPTQ in **float32**, not GPTQModel's auto-selected bf16: 1.9× faster on this CPU (no AVX512-BF16).
3. **200 items per task** in the EXP1/EXP2 seed sweeps (lm-eval is ~60 % of a GPTQ cell); 500 only for anchor cells.
4. GPTQ W3 at 3 seeds; EXP2 at 3 seeds per source, GPTQ W4 only.
5. EXP3: run the 0-shot factorial on 135M plus 2 few-shot variants; on 360M only the factors that move 135M.
6. EXP4 is cheap (≈ 2–3 h) — keep it whole, but fix the launcher/thread protocol first (§6.6).
"""
p = os.path.join(D, "REPORT.md"); s = open(p).read()
s = re.sub(r"## 4\. Extrapolated CPU budget.*?(?=## 5\.)", lambda m: sec + "\n", s, flags=re.S)
open(p, "w").write(s)
print("ok")
