"""Revision sections for PAPER_TABLES.md, computed from EXISTING records only (plus the optional RTN runs in
revision/rtn_runs.jsonl). Called from paper_tables.py as build(globals()); returns Markdown lines and writes CSVs into
feasibility/revision/.  Items refer to the reviewer-response list (1 pooled SD, 2 NLL scale, 5 variance sources,
6 seeds needed, 7 determinism, 8 Hessian share, 9 RTN)."""
import csv, json, math, os, statistics as st
from scipy import stats

REV = os.path.dirname(os.path.abspath(__file__))


def _csv(name, header, rows):
    with open(os.path.join(REV, name), "w", newline="") as fh:
        wr = csv.writer(fh); wr.writerow(header); wr.writerows(rows)
    return f"`revision/{name}`"


def build(g):
    S, P, cite, q, m1, summ, pooled_sd, welch, holm = (g[k] for k in ("S", "P", "cite", "q", "m1", "summ", "pooled_sd", "welch", "holm"))
    out = []; w = out.append
    dense_wt, dense_wt_eager, dense_c4, qwen_dense = g["dense_wt"], g["dense_wt_eager"], g["dense_c4"], g["qwen_dense"]
    w("# Revision analyses (from existing records; generated by `revision/revision_sections.py`)\n")

    # ------------------------------------------------------------------ 1. pooled SD audit
    w("## R1. Pooled SD: every Δ / pooled SD value, unweighted vs df-weighted\n")
    w("Formula used everywhere now: pooled SD = sqrt(Σ(nᵢ−1)sᵢ² / Σ(nᵢ−1)). The first version of these tables (commit `5a6284f`)")
    w("used the unweighted mean of the two variances, sqrt((s₁²+s₂²)/2), in section 2, and divided section-5 factors by the")
    w("SDPA 128×512 W4 seed SD (0.0209) instead of a pooled SD. Values that change:\n")
    rows = []
    for lab, za, zb, d, *_ in g["WLrows"]:
        old = d / ((za["sd"] ** 2 + zb["sd"] ** 2) / 2) ** 0.5; new = d / pooled_sd(za, zb)
        rows.append(["2 window length", lab, f"{d:+.4f}", f"{old:.3f}", f"{new:.3f}", "yes" if abs(old - new) > 0.005 else "no"])
    for b in (4, 3):
        for ev, own, other in (("wt_ppl", "wikitext2", "c4"), ("c4_ppl", "c4", "wikitext2")):
            za, zb = g["DOM"][(b, own, ev)][0], g["DOM"][(b, other, ev)][0]; d = zb["mean"] - za["mean"]
            old = d / ((za["sd"] ** 2 + zb["sd"] ** 2) / 2) ** 0.5; new = d / pooled_sd(za, zb)
            rows.append(["3 source × eval", f"W{b} {ev}", f"{d:+.4f}", f"{old:.3f}", f"{new:.3f}", "yes" if abs(old - new) > 0.005 else "no (equal n)"])
    sd_sdpa = S["SmolLM2-135M · GPTQ W4 g128 · 128×512 · SDPA"][0]["sd"]
    for lab, v, *_ in g["F"]:
        if lab.startswith("S4:"): continue
        rows.append(["5 factors", lab, f"{v:.4f}", f"{v / sd_sdpa:.2f} (÷ SDPA SD 0.0209)", f"{v / g['W4P']:.2f} (÷ pooled {g['W4P']:.4f})", "yes"])
    w("| table | quantity | Δ | old ratio | df-weighted ratio | changed |")
    w("|---|---|---|---|---|---|")
    for r in rows: w("| " + " | ".join(r) + " |")
    w(f"\nExported: {_csv('R1_pooled_sd_values.csv', ['table', 'quantity', 'delta', 'old_ratio', 'df_weighted_ratio', 'changed'], rows)}. "
      "The S4 factor table (section 5) was created after the fix and always used the df-weighted pooled SD.\n")

    # ------------------------------------------------------------------ 2. NLL scale
    w("## R2. Damage on the NLL scale, D = ln(ppl_compressed / ppl_dense)\n")
    allrows = []
    for name, (z, src, cfg, dense) in S.items():
        for i, v in enumerate(z["v"]):
            allrows.append([name, i, "WikiText-2 40×2048", f"{v:.6f}", f"{dense:.6f}", f"{math.log(v / dense):.6f}", P[src[0]]])
    for b in (4, 3):
        for x in range(3):
            v = m1("F1", f"w{b}_s{x}", "c4_ppl")
            allrows.append([f"SmolLM2-135M · GPTQ W{b} · 128×2048 · eager", x, "C4-val 256×2048", f"{v:.6f}", f"{dense_c4:.6f}", f"{math.log(v / dense_c4):.6f}", P["F1"]])
        for src in ("wikitext2", "c4"):
            for x in range(3):
                for ev, dref, lab in (("wt_ppl", dense_wt_eager, "WikiText-2 40×2048"), ("c4_ppl", dense_c4, "C4-val 256×2048")):
                    v = m1("F3", f"w{b}_{src}_s{x}", ev)
                    allrows.append([f"SmolLM2-135M · GPTQ W{b} · 128×512 · {src}-calibrated · eager", x, lab, f"{v:.6f}", f"{dref:.6f}", f"{math.log(v / dref):.6f}", P["F3"]])
    s4 = g["s4"]
    if len(s4) == 12:
        grid = []
        for L in (512, 1024, 2048):
            for bo in (0, 1):
                dn, w4 = s4[f"dense_ctx{L}_bos{bo}"]["wt_ppl"], s4[f"w4_ctx{L}_bos{bo}"]["wt_ppl"]
                grid.append((f"ctx{L}/{'BOS' if bo else 'noBOS'}", L, bo, dn, w4, w4 - dn, math.log(w4 / dn)))
                allrows.append(["SmolLM2-135M · GPTQ W4 s0 · 128×512 · eager (S4)", 0, f"S4 ctx {L}, BOS {bo}", f"{w4:.6f}", f"{dn:.6f}", f"{math.log(w4 / dn):.6f}", "results/final_S4_ppl.jsonl"])
        w(f"**S4 six-protocol grid** (SmolLM2-135M, eager; one W4 checkpoint, sha256 `9b3c5e64…`; {cite('results/final_S4_ppl.jsonl')}):\n")
        w("| cell | dense ppl | W4 ppl | Δ ppl (W4 − dense) | D (nats) |")
        w("|---|---|---|---|---|")
        for c, L, bo, dn, w4, dp, D in grid: w(f"| {c} | {dn:.4f} | {w4:.4f} | {dp:+.4f} | {D:.4f} |")
        dps, Ds = [r[5] for r in grid], [r[6] for r in grid]
        w("")
        w(f"- **Headline on both scales.** Δ ppl ranges {min(dps):.2f}–{max(dps):.2f} (max/min {max(dps) / min(dps):.2f}, "
          f"relative spread {100 * (max(dps) - min(dps)) / min(dps):.0f} %). D ranges {min(Ds):.4f}–{max(Ds):.4f} nats "
          f"(max/min {max(Ds) / min(Ds):.2f}, relative spread {100 * (max(Ds) - min(Ds)) / min(Ds):.0f} %).")
        w("- Most of the ppl-scale spread is the dense baseline moving with context (dense ppl 14.49 → 20.10): on the NLL scale the")
        w(f"  protocol changes the measured damage by {100 * (max(Ds) - min(Ds)) / min(Ds):.0f} %, not {100 * (max(dps) - min(dps)) / min(dps):.0f} %.")
        pair = []
        for i in range(len(grid)):
            for j in range(i + 1, len(grid)):
                a, b = grid[i], grid[j]
                pair.append([a[0], b[0], f"{b[5] - a[5]:+.4f}", f"{b[6] - a[6]:+.5f}"])
        w(f"- Pairwise differences of all 15 cell pairs (Δppl and D): {_csv('R2_s4_pairwise.csv', ['cell_a', 'cell_b', 'delta_ppl_diff', 'D_diff'], pair)}; "
          f"grid: {_csv('R2_s4_grid.csv', ['cell', 'context', 'bos', 'dense_ppl', 'w4_ppl', 'delta_ppl', 'D'], [[c, L, bo, f'{dn:.6f}', f'{w4:.6f}', f'{dp:.6f}', f'{D:.6f}'] for c, L, bo, dn, w4, dp, D in grid])}.\n")
    w(f"Every perplexity value used in these tables with its dense reference and D: "
      f"{_csv('R2_all_ppl_D.csv', ['setting', 'seed', 'eval_set_protocol', 'ppl', 'dense_ppl', 'D_nats', 'results_file'], allrows)} "
      f"({len(allrows)} rows). Dense references: SDPA WikiText-2 {dense_wt:.6f}, eager WikiText-2 {dense_wt_eager:.6f}, eager C4 {dense_c4:.6f}, "
      f"Qwen eager WikiText-2 {qwen_dense:.6f}.\n")

    # ------------------------------------------------------------------ 5. variance sources
    w("## R5. Run-to-run vs calibration-seed variance per configuration\n")
    w("Run-to-run variance = pooled within-group variance over all same-seed repeats of one command; seed variance = the SD²")
    w("of that configuration's seed set (which itself contains one run-to-run draw per seed).\n")
    groups = g["groups"]
    SRC = {"GPTQ W4 · 128×512 · SDPA (default)": "real_step1 s0, real_step2_c4val rebuild, real_step2_det rep2/rep3",
           "GPTQ W4 · 128×512 · eager": "S1/S3 anchors, final_S2_anchor r1–r5, real_step2_det eager1/2",
           "GPTQ W4 · 128×2048 · eager": "final_S1 w4_s0 + w4_s0_rep", "GPTQ W3 · 128×2048 · eager": "final_S1 w3_s0 + w3_s0_rep",
           "GPTQ W3 · 128×512 · eager (S3, WT-cal)": "final_S3 w3_wikitext2_s0 + _rep", "Wanda 60 % / 2:4 / 70 % (seed 0)": "final_S2_wanda s0 + s0_rep"}
    rep = {
        "GPTQ W4 · 128×512 · SDPA (default)": ([[v for _, v, _ in groups["default (SDPA, 4 threads)"]]], S["SmolLM2-135M · GPTQ W4 g128 · 128×512 · SDPA"][0]),
        "GPTQ W4 · 128×512 · eager": ([[v for _, v, _ in groups["eager, 4 threads"]]], S["SmolLM2-135M · GPTQ W4 g128 · 128×512 · eager"][0]),
        "GPTQ W4 · 128×2048 · eager": ([[m1("F1", "w4_s0"), m1("F1", "w4_s0_rep")]], S["SmolLM2-135M · GPTQ W4 g128 · 128×2048 · eager"][0]),
        "GPTQ W3 · 128×2048 · eager": ([[m1("F1", "w3_s0"), m1("F1", "w3_s0_rep")]], S["SmolLM2-135M · GPTQ W3 g128 · 128×2048 · eager"][0]),
        "GPTQ W3 · 128×512 · eager (S3, WT-cal)": ([[m1("F3", "w3_wikitext2_s0"), m1("F3", "w3_wikitext2_s0_rep")]], S["SmolLM2-135M · GPTQ W3 g128 · 128×512 · eager"][0]),
        "Wanda 60 % / 2:4 / 70 % (seed 0)": ([[q("F2w", f"final_S2_wanda_{k}_s0"), q("F2w", f"final_S2_wanda_{k}_s0_rep")] for k in ("u60", "24", "u70")], None),
    }
    w("| configuration | repeat groups | runs | run-to-run SD | seed SD (n) | run var / seed var | sources |")
    w("|---|---|---|---|---|---|---|")
    for lab, (grps, zs) in rep.items():
        num = sum(sum((v - st.mean(gp)) ** 2 for v in gp) for gp in grps); den = sum(len(gp) - 1 for gp in grps)
        rsd = (num / den) ** 0.5
        seed = f"{zs['sd']:.4f} ({zs['n']})" if zs else "0.32 / 1.55 / 329 (3)"
        ratio = f"{(rsd / zs['sd']) ** 2:.3f}" if zs else "0"
        w(f"| {lab} | {len(grps)} | {sum(len(gp) for gp in grps)} | {rsd:.4f} | {seed} | {ratio} | "
          f"{SRC[lab]} |")
    w("")
    w("- **SDPA default path: run-to-run noise exceeds the seed spread** (run SD 0.038 vs seed SD 0.021 → ratio > 1). The Step 1")
    w("  W4 128×512 seed SD therefore cannot be read as a calibration-seed effect at all; it is within the noise.")
    w("- Eager path: run-to-run variance is ≤ 0.7 % of the seed variance in every configuration with repeats (0 where repeats were")
    w("  bit-identical); Wanda repeats are bit-identical. Seed SDs on the eager path and for Wanda are calibration-seed effects.\n")

    # ------------------------------------------------------------------ 6. seeds needed
    w("## R6. Seeds per arm for 80 % power (α = 0.05, two-sided, two-sample)\n")
    w("Normal approximation: n = ⌈2 (z₀.₉₇₅ + z₀.₈₀)² σ² / δ²⌉ = ⌈15.7 σ²/δ²⌉ with σ = the setting's observed seed SD (a point")
    w("estimate from 3–10 seeds; with the upper χ² CI bound the numbers would be several times larger). Minimum shown is 2.\n")
    deltas = (0.1, 0.25, 0.5, 1, 2)
    zz = (stats.norm.ppf(0.975) + stats.norm.ppf(0.8)) ** 2
    w("| setting | σ (n) | " + " | ".join(f"δ = {d}" for d in deltas) + " |")
    w("|---|---|" + "---|" * len(deltas))
    prow = []
    for name, (z, *_r) in S.items():
        ns = [max(2, math.ceil(2 * zz * z["sd"] ** 2 / d ** 2)) for d in deltas]
        w(f"| {name} | {z['sd']:.4f} ({z['n']}) | " + " | ".join(str(n) if n <= 10000 else "> 10⁴" for n in ns) + " |"); prow.append([name, z["sd"], z["n"], *ns])
    w("")
    w("- SDPA W4 128×512: its observed seed SD (0.021) is *below* the run-to-run SD of that path (0.038, R5), so the row understates")
    w("  the noise; with σ = 0.038 the counts are 3 / 2 / 2 / 2 / 2.")
    w("- Wanda 70 %: the per-seed values (917, 976, 1515) are far from normal, so the normal approximation (and the χ² SD CI) does")
    w("  not apply; the row only says that no feasible number of seeds resolves differences at this scale.")
    w(f"\nExported: {_csv('R6_seeds_needed.csv', ['setting', 'sd', 'n_observed', *[f'n_delta_{d}' for d in deltas]], prow)}.\n")

    # ------------------------------------------------------------------ 7. determinism classification
    w("## R7. Determinism: quantization vs evaluation nondeterminism\n")
    w("**What was hashed.** `ckpt_sha256` = SHA-256 over the raw bytes of every `*.safetensors` file in the saved GPTQModel checkpoint")
    w("directory, files sorted by name and fed into one hash in that order (`final_S1_run.py` l.104–106, `final_S3_run.py` l.108–110,")
    w("`final_S4_ppl.py` l.62–64, `step2_detcmp.py` l.7–9, `final_S2_run.py` l.44–47). For these models the directory holds a single")
    w("`model.safetensors` (packed int32 qweight, scales, zeros, g_idx, plus unquantized embeddings/norms/lm_head). Not hashed:")
    w("`config.json`, `quantize_config.json`, `generation_config.json`, tokenizer files and `quant_log.csv`. Equal hashes therefore")
    w("mean bit-identical quantized weights; a different perplexity with an equal hash can only come from evaluation.\n")
    det = [("S1 anchor_a", m1("F1", "anchor_a"), g["R"]["F1"]["anchor_a"]["ckpt_sha256"]),
           ("S3 anchor_a (the 17.664706 run)", m1("F3", "anchor_a"), g["R"]["F3"]["anchor_a"]["ckpt_sha256"]),
           ("S1/S3 anchor_b, S2 r1–r5, step 2 eager1/2 (modal)", 17.66059890313337, g["R"]["F1"]["anchor_b"]["ckpt_sha256"]),
           ("S4 W4 ctx2048 no-BOS", s4["w4_ctx2048_bos0"]["wt_ppl"] if s4 else float("nan"), (s4.get("w4_ctx2048_bos0") or {}).get("ckpt_sha256", ""))]
    modal = g["R"]["F1"]["anchor_b"]["ckpt_sha256"]
    w("| run | WT-ppl | checkpoint sha256 (16) | same weights as modal? | classification |")
    w("|---|---|---|---|---|")
    for lab, v, h in det:
        same = h == modal
        cls = "— (reference)" if "modal" in lab else ("**evaluation** nondeterminism" if same else "**quantization** nondeterminism")
        w(f"| {lab} | {v:.6f} | `{h[:16]}` | {'yes' if same else 'no'} | {cls} |")
    w("")
    w("The 17.664706 eager run (S3 anchor_a) has a different checkpoint hash (`bfb81cf2…`) from the modal `9b3c5e64…`: its weights")
    w("differ, so it is **quantization** nondeterminism. The S4 value 17.664362 has the modal hash, so it is **evaluation**")
    w("nondeterminism (same weights, same 81,880 targets). On the default SDPA path both outcomes also had different hashes")
    w("(`72b61b9e…` vs `3c9ab62e…`): quantization nondeterminism. Default-path Step 1 (Session B) recorded no hash.\n")

    # ------------------------------------------------------------------ 8. Hessian share
    w("## R8. Mechanism data: first-token share of the Hessian (REPORT.md A.6)\n")
    w("Computed by `probe_positions.py` on the **dense fp32** model (transformers' default SDPA attention) over the first 8 seed-0")
    w("WikiText-2 calibration windows at L = 512 and at L = 2048. For each layer, a forward pre-hook takes the `mlp.down_proj`")
    w("input x_t (one vector per token position t) and accumulates ‖x_t‖₂² per position over the 8 windows. GPTQ's Hessian is")
    w("H = (2/N) Σ_t x_t x_tᵀ, and trace(x xᵀ) = ‖x‖², so **share_pos0 = Σ_windows ‖x_0‖² / Σ_windows Σ_t ‖x_t‖² = the position-0")
    w("share of trace(H)** (equivalently of the sum of H's diagonal). It is not a Frobenius-norm or eigenvalue share.")
    w("`share_pos0_3` is the same for positions 0–3; `pos0_over_median` = ‖x_0‖² / median_t>0 ‖x_t‖² (summed over windows).\n")
    for f, mdl in (("results/real_diag_probe_positions_smol_all.json", "SmolLM2-135M"), ("results/real_diag_probe_positions_qwen05.json", "Qwen2.5-0.5B")):
        d = json.load(open(os.path.join(os.path.dirname(REV), f)))
        layers = sorted({int(k) for L in d for k in d[L]})
        rows = [[mdl, int(L), i, *(f"{d[L][str(i)][k]:.6g}" for k in ("share_pos0_pct", "share_pos0_3_pct", "pos0_over_median")), d[L][str(i)]["max_pos"]]
                for L in sorted(d, key=int) for i in layers]
        name = f"R8_hessian_pos0_share_{mdl.split('-')[0].lower().replace('.', '')}.csv"
        top = sorted(layers, key=lambda i: -d["512"][str(i)]["share_pos0_pct"])[:3]
        w(f"- {mdl}: {len(layers)} layers × L ∈ {{512, 2048}} → {_csv(name, ['model', 'window_L', 'layer', 'share_pos0_pct', 'share_pos0_3_pct', 'pos0_over_median', 'max_pos'], rows)} "
          f"(source {cite(f)}); largest position-0 shares at L=512: " +
          ", ".join(f"layer {i} {d['512'][str(i)]['share_pos0_pct']:.1f} % → {d['2048'][str(i)]['share_pos0_pct']:.1f} %" for i in top) + ".")
    w("")

    # ------------------------------------------------------------------ 9. RTN
    rtn_p = os.path.join(REV, "rtn_runs.jsonl")
    rtn = {json.loads(l)["run_id"]: json.loads(l) for l in open(rtn_p)} if os.path.exists(rtn_p) else {}
    w("## R9. GPTQ vs round-to-nearest (RTN)\n")
    if len(rtn) < 16:
        w(f"RTN results incomplete ({len(rtn)}/16 cells in `revision/rtn_runs.jsonl`).\n")
        return out
    w("RTN = GPTQ's symmetric min-max quantizer applied per row and 128-column group without calibration or error compensation")
    w("(`revision/rtn_eval.py`), all decoder-layer Linear modules, weights cast to bf16, eager attention; deterministic (weights hash")
    w(f"recorded per run). Results: {cite('revision/rtn_runs.jsonl')}.\n")
    w("| RTN | WT-ppl | D | C4-ppl | D | " + " | ".join(f"ctx{L}/{'BOS' if b else 'noBOS'}" for L in (512, 1024, 2048) for b in (0, 1)) + " |")
    w("|---|---|---|---|---|" + "---|" * 6)
    for b in (4, 3):
        r = lambda k: rtn[f"rtn_w{b}_{k}"]["ppl"]
        w(f"| W{b} g128 | {r('wt'):.3f} | {math.log(r('wt') / dense_wt_eager):.4f} | {r('c4'):.3f} | {math.log(r('c4') / dense_c4):.4f} | " +
          " | ".join(f"{r(f'ctx{L}_bos{bo}'):.3f}" for L in (512, 1024, 2048) for bo in (0, 1)) + " |")
    w("")
    # GPTQ - RTN per setting and seed
    cmp_rows, summ_rows = [], []
    def compare(label, vals, rtn_v, dref, src):
        diffs = [v - rtn_v for v in vals]; Ds = [math.log(v / rtn_v) for v in vals]  # D difference = ln(gptq/rtn)
        m = st.mean(diffs); disagree = sum((x > 0) != (m > 0) for x in diffs)
        for i, (x, y) in enumerate(zip(diffs, Ds)): cmp_rows.append([label, i, f"{vals[i]:.6f}", f"{rtn_v:.6f}", f"{x:+.6f}", f"{y:+.6f}"])
        summ_rows.append((label, len(vals), m, min(diffs), max(diffs), st.mean(Ds), disagree, src))
    for b in (4, 3):
        rw, rc = rtn[f"rtn_w{b}_wt"]["ppl"], rtn[f"rtn_w{b}_c4"]["ppl"]
        for name, (z, src, cfg, dense) in S.items():
            if f"GPTQ W{b}" in name and "SmolLM2" in name: compare(f"{name} · WT", z["v"], rw, dense, src[0])
        compare(f"SmolLM2-135M · GPTQ W{b} · 128×2048 · eager · C4", [m1("F1", f"w{b}_s{x}", "c4_ppl") for x in range(3)], rc, dense_c4, "F1")
        for srcc in ("wikitext2", "c4"):
            for ev, rv, lab in (("wt_ppl", rw, "WT"), ("c4_ppl", rc, "C4")):
                if srcc == "wikitext2" and ev == "wt_ppl": continue  # identical data to the section-1 "128×512 · eager · WT" row
                compare(f"SmolLM2-135M · GPTQ W{b} · 128×512 · {srcc}-cal · eager · {lab}", [m1("F3", f"w{b}_{srcc}_s{x}", ev) for x in range(3)], rv, None, "F3")
    for L in (512, 1024, 2048):
        for bo in (0, 1):
            compare(f"SmolLM2-135M · GPTQ W4 s0 · 128×512 · eager · S4 ctx{L}/{'BOS' if bo else 'noBOS'}", [s4[f"w4_ctx{L}_bos{bo}"]["wt_ppl"]],
                    rtn[f"rtn_w4_ctx{L}_bos{bo}"]["ppl"], None, "S4")
    w("GPTQ − RTN (negative = GPTQ better), per setting; ln-ratio = ln(ppl_GPTQ / ppl_RTN) = D_GPTQ − D_RTN on the same eval set:\n")
    w("| GPTQ setting · eval | seeds | mean Δ ppl | min | max | mean ln-ratio | seeds disagreeing in sign with the mean |")
    w("|---|---|---|---|---|---|---|")
    for lab, n, m, lo, hi, mD, dis, src in summ_rows:
        w(f"| {lab} | {n} | {m:+.3f} | {lo:+.3f} | {hi:+.3f} | {mD:+.4f} | {dis}/{n} |")
    nseed = sum(r[1] for r in summ_rows if r[1] > 1); ndis = sum(r[6] for r in summ_rows if r[1] > 1)
    flips = [r for r in summ_rows if r[3] < 0 < r[4]]; worse = [r for r in summ_rows if r[2] > 0]
    w("")
    w(f"- GPTQ is better than RTN on average in {len(summ_rows) - len(worse)}/{len(summ_rows)} settings; "
      f"{'no setting has a positive mean (GPTQ worse)' if not worse else 'GPTQ is worse on average in: ' + '; '.join(r[0] for r in worse)}.")
    w(f"- Settings where individual seeds straddle zero (advantage changes sign between seeds): {len(flips)}"
      + (": " + "; ".join(r[0] for r in flips) if flips else "") + ".")
    w(f"- Single-seed comparisons that disagree in sign with their multi-seed mean: **{ndis} of {nseed}** seed-level comparisons "
      f"(over the {sum(1 for r in summ_rows if r[1] > 1)} multi-seed settings).")
    multi = [r for r in summ_rows if r[1] > 1]
    dev = max(max(abs(r[3] - r[2]), abs(r[4] - r[2])) / abs(r[2]) for r in multi)
    w(f"- Magnitude: a single seed's GPTQ − RTN deviates from its setting's mean by at most {100 * dev:.0f} % of the mean; the seed choice never")
    w("  changes the conclusion. What changes the size of GPTQ's advantage is the protocol: on the NLL scale it ranges")
    w(f"  {min(-r[5] for r in summ_rows if 'W4' in r[0]):.3f}–{max(-r[5] for r in summ_rows if 'W4' in r[0]):.3f} nats at W4 (C4 eval and 2048-token calibration smallest,"
      f" 512-token context largest) and {min(-r[5] for r in summ_rows if 'W3' in r[0]):.2f}–{max(-r[5] for r in summ_rows if 'W3' in r[0]):.2f} nats at W3.")
    w("- Caveat: RTN is evaluated with eager attention; the SDPA GPTQ rows compare across attention paths (≤0.15 ppl, section 4).")
    w(f"\nPer-seed comparisons: {_csv('R9_gptq_minus_rtn.csv', ['setting', 'seed', 'gptq_ppl', 'rtn_ppl', 'delta_ppl', 'ln_ratio'], cmp_rows)}.\n")
    return out
